// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbN4T9vcwSD4wdhxyxWyig8_xOJe3T2ec',
    appId: '1:971198948181:web:b00b2a34b35772ff20c5dc',
    messagingSenderId: '971198948181',
    projectId: 'lidas-42485',
    authDomain: 'lidas-42485.firebaseapp.com',
    storageBucket: 'lidas-42485.firebasestorage.app',
    measurementId: 'G-HQB7F6NR7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwx9lMrG-EKxgFKi485V2wI3O7xjQb6aA',
    appId: '1:971198948181:android:b70fbd84682b934920c5dc',
    messagingSenderId: '971198948181',
    projectId: 'lidas-42485',
    storageBucket: 'lidas-42485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rnSYfP-rGc40zUqPuOm0JUB4tqdHL4I',
    appId: '1:971198948181:ios:5c9743c4882f69cd20c5dc',
    messagingSenderId: '971198948181',
    projectId: 'lidas-42485',
    storageBucket: 'lidas-42485.firebasestorage.app',
    iosBundleId: 'com.example.lidas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rnSYfP-rGc40zUqPuOm0JUB4tqdHL4I',
    appId: '1:971198948181:ios:5c9743c4882f69cd20c5dc',
    messagingSenderId: '971198948181',
    projectId: 'lidas-42485',
    storageBucket: 'lidas-42485.firebasestorage.app',
    iosBundleId: 'com.example.lidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbN4T9vcwSD4wdhxyxWyig8_xOJe3T2ec',
    appId: '1:971198948181:web:f1af4e0727f164da20c5dc',
    messagingSenderId: '971198948181',
    projectId: 'lidas-42485',
    authDomain: 'lidas-42485.firebaseapp.com',
    storageBucket: 'lidas-42485.firebasestorage.app',
    measurementId: 'G-BPQSQSSMNC',
  );
}
